image: ubuntu:20.04

stages:
  - build
  - test

before_script:
  - apt-get update
  - DEBIAN_FRONTEND=noninteractive apt-get -yq install git build-essential cmake lcov
  - git submodule sync --recursive
  - git submodule update --init --recursive


build:
  stage: build
  artifacts:
    untracked: true
  script:
    - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS='-O0 -g -pg -fprofile-arcs -ftest-coverage' -DCMAKE_EXE_LINKER_FLAGS=-pg -DCMAKE_SHARED_LINKER_FLAGS=-pg .. && make

test:
  stage: test
  dependencies:
    - build
  artifacts:
    untracked: true
  script:
    - cd build
    - sh -c './cpp-base64X-Test'
    - lcov -d . -c --output-file app-raw.info
    - lcov --remove app-raw.info ../3rdParty '/usr/include/*' -o app.info
    - lcov -l app.info
